language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rla1gus1tlr1/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true rla1gus1tlr1/react-test-app npm test

after_success:
  - docker build -t rla1gus1tlr1/docker-frontend ./frontend
  - docker build -t rla1gus1tlr1/docker-backend ./backend
  - docker build -t rla1gus1tlr1/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push rla1gus1tlr1/docker-frontend
  - docker push rla1gus1tlr1/docker-backend
  - docker push rla1gus1tlr1/docker-nginx

